### ISSUE TITLE
I am not able to perform a click when holding alt-key (optional context menus or dragging items in finder)

### ISSUE THREAD

**Issue by martinengelke** [franzbu/EnhancedSpaces.spoon#7]
Using alt as the standard modifier for mouse dragging is maybe not the best option, since at least I am not able to alt click a finder item in the side bar and choose an option.

**Comment by franzbu** [comment]
It is not easy to find modifiers that are not used in any other way by the plethora of apps all of us have on our Macs. A sensible solution is a [hyper key](https://github.com/franzbu/EnhancedSpaces.spoon/tree/main?tab=readme-ov-file#hyper-key)

I'd rather not make any changes here because, as has been pointed out, it will collide with sombody else's preferences, and regardless of which modifier one prefers, it is simple enough to change it in EnhancedSpaces' config.

**Comment by martinengelke** [comment]
I will go for hyper key anyway but I am not completely finished with my config and that's why I at least said: 
Don't pick it as default :P Rather do a triple keystroke which is surely not interfering with other things to be safe than getting complaints 😄
